// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvo_A-3OJBbcpey0xP2qngVGy1Tob_QRQ',
    appId: '1:16017087609:web:f6cc6693df3f4fbba708a8',
    messagingSenderId: '16017087609',
    projectId: 'tiktok-clonecoding-ian',
    authDomain: 'tiktok-clonecoding-ian.firebaseapp.com',
    databaseURL: 'https://tiktok-clonecoding-ian-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiktok-clonecoding-ian.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1XTNCHZrVoH0-yA_DNYVKkEksDpiat4',
    appId: '1:16017087609:android:72acdd735f87ebbda708a8',
    messagingSenderId: '16017087609',
    projectId: 'tiktok-clonecoding-ian',
    databaseURL: 'https://tiktok-clonecoding-ian-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiktok-clonecoding-ian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdyUDwu4AC_C8FLxWlEEHH6L71FkUqw8k',
    appId: '1:16017087609:ios:983ce5f7e32b3400a708a8',
    messagingSenderId: '16017087609',
    projectId: 'tiktok-clonecoding-ian',
    databaseURL: 'https://tiktok-clonecoding-ian-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tiktok-clonecoding-ian.appspot.com',
    iosBundleId: 'com.example.tiktokClonetest',
  );
}
